export {Home} from './homepage/homepage';
export {Login} from './login-page/login-page';
export {Register} from './register-page/register-page';
export {IdeaDetail} from './idea-detail-page/idea-detail-page';
export {About} from './about/about';
export {Admin} from './admin/admin';
export { Users } from "./user/user";
export {UserDashboard} from './user-dashboard/user-dashboard';
export {UserProfile} from './user-profile/user-profile';
export {UserPassword} from './user-password/user-password';
export {Departments} from './department/department';
